import type { Metadata } from 'next'
import { Patrick_Hand } from 'next/font/google'
import { ThemeProvider } from '@/provider/theme-provider'
import './globals.css'

const patrickHand = Patrick_Hand({
  variable: '--font-patrick-hand',
  weight: '400',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${patrickHand.className} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
